# Generated by Django 6.0.5 on 2026-05-14 18:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('nit', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Solo se permiten números.', regex='^\\d+$')])),
                ('direccion', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Solo se permiten números.', regex='^\\d+$')])),
                ('estado', models.CharField(choices=[('abierto', 'Abierto'), ('cerrado', 'Cerrado')], default='abierto', max_length=20)),
            ],
        ),
    ]
