# Generated by Django 6.0.5 on 2026-05-17 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurante',
            name='color_principal',
            field=models.CharField(default='#e74c3c', help_text='Color principal en formato HEX (ej: #e74c3c).', max_length=7),
        ),
        migrations.AddField(
            model_name='restaurante',
            name='logo',
            field=models.ImageField(blank=True, help_text='Logo del restaurante.', null=True, upload_to='restaurantes/logos/'),
        ),
        migrations.AddField(
            model_name='restaurante',
            name='portada',
            field=models.ImageField(blank=True, help_text='Imagen de fondo del banner principal.', null=True, upload_to='restaurantes/portadas/'),
        ),
        migrations.AddField(
            model_name='restaurante',
            name='slogan',
            field=models.CharField(blank=True, default='', help_text='Frase corta que describe tu restaurante.', max_length=200),
        ),
    ]
