# Generated by Django 6.0.5 on 2026-05-17 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_alter_producto_imagen'),
        ('restaurantes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriaproducto',
            options={'ordering': ['nombre']},
        ),
        migrations.AddField(
            model_name='categoriaproducto',
            name='activa',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterUniqueTogether(
            name='categoriaproducto',
            unique_together={('restaurante', 'nombre')},
        ),
    ]
