# Generated by Django 6.0.5 on 2026-06-05 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_alter_categoriaproducto_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='cubierto_por_tiquetera',
            field=models.BooleanField(default=False, help_text='Si está activo, este producto no se cobra cuando el consumo es por tiquetera.', verbose_name='Cubierto por tiquetera'),
        ),
    ]
