# Generated by Django 6.0.5 on 2026-05-14 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantes', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='restaurante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='restaurantes.restaurante'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(blank=True, choices=[('admin', 'Administrador'), ('mesero', 'Mesero'), ('cajero', 'Cajero'), ('domiciliario', 'Domiciliario')], max_length=20, null=True),
        ),
    ]
