# Generated by Django 6.0.5 on 2026-05-19 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuario_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(blank=True, choices=[('admin', 'Administrador'), ('mesero', 'Mesero'), ('domiciliario', 'Domiciliario')], max_length=20, null=True),
        ),
    ]
