# Generated by Django 6.0.5 on 2026-05-20 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_usuario_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(blank=True, choices=[('admin', 'Administrador'), ('mesero', 'Mesero'), ('domiciliario', 'Domiciliario'), ('cajero', 'Cajero')], max_length=20, null=True),
        ),
    ]
