# Generated by Django 6.0.5 on 2026-05-23 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0005_alter_categoriaproducto_options_and_more'),
        ('restaurantes', '0002_restaurante_color_principal_restaurante_logo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoDomicilio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_preparacion', 'En preparación'), ('listo', 'Listo'), ('entregado', 'Entregado')], default='pendiente', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cliente_nombre', models.CharField(max_length=150)),
                ('cliente_telefono', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=255)),
                ('referencia', models.TextField(blank=True, default='')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('restaurante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_domicilio', to='restaurantes.restaurante')),
            ],
        ),
        migrations.CreateModel(
            name='ItemPedidoDomicilio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('nota', models.TextField(blank=True, default='')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='domicilios.pedidodomicilio')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items_domicilio', to='productos.producto')),
            ],
        ),
    ]

