# Generated by Django 6.0.5 on 2026-05-23 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domicilios', '0001_initial'),
        ('usuarios', '0004_alter_usuario_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidodomicilio',
            name='domiciliario',
            field=models.ForeignKey(blank=True, limit_choices_to={'rol': 'domiciliario'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='domicilios_asignados', to='usuarios.usuario'),
        ),
        migrations.AddField(
            model_name='pedidodomicilio',
            name='estado_entrega',
            field=models.CharField(blank=True, choices=[('recibido', 'Pedido recibido'), ('en_camino', 'Pedido en camino'), ('entregado', 'Pedido entregado')], default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pedidodomicilio',
            name='fecha_en_camino',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedidodomicilio',
            name='fecha_entregado',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedidodomicilio',
            name='fecha_recibido',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]

