# Generated by Django 6.0.5 on 2026-05-17 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comandas', '0002_comanda_estado_comanda_fecha_creacion_comanda_mesero_and_more'),
        ('productos', '0005_alter_categoriaproducto_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcomanda',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto'),
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
