# Generated by Django 6.0.5 on 2026-05-18 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comandas', '0003_alter_itemcomanda_producto_delete_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='comanda',
            name='tipo_consumo',
            field=models.CharField(choices=[('normal', 'Normal'), ('tiquetera', 'Tiquetera')], default='normal', max_length=20),
        ),
    ]
