# Generated by Django 6.0.5 on 2026-05-19 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comandas', '0004_comanda_tipo_consumo'),
        ('tiqueteras', '0002_plantiquetera_tipo_servicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='comanda',
            name='tiquetera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comandas', to='tiqueteras.tiquetera'),
        ),
    ]
