# Generated by Django 6.0.5 on 2026-06-05 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comandas', '0005_comanda_tiquetera'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[],
            database_operations=[],
        ),
    ]
