# Generated by Django 6.0.5 on 2026-06-05 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comandas', '0005_comanda_tiquetera'),
    ]

    operations = [
        migrations.RunSQL(
            sql='ALTER TABLE comandas_itemcomanda DROP COLUMN precio_unitario',
            reverse_sql='ALTER TABLE comandas_itemcomanda ADD COLUMN precio_unitario numeric(10,2)'
        ),
    ]
