# Generated by Django 6.0.5 on 2026-05-18 18:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comandas', '0004_comanda_tipo_consumo'),
        ('restaurantes', '0002_restaurante_color_principal_restaurante_logo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanTiquetera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad_consumos', models.PositiveIntegerField()),
                ('dias_vigencia', models.PositiveIntegerField()),
                ('permite_multiples_consumos', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('restaurante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes_tiquetera', to='restaurantes.restaurante')),
            ],
        ),
        migrations.CreateModel(
            name='Tiquetera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_nombre', models.CharField(max_length=150)),
                ('cliente_telefono', models.CharField(blank=True, max_length=20)),
                ('saldo_consumos', models.PositiveIntegerField(editable=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('activa', models.BooleanField(default=True)),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tiqueteras.plantiquetera')),
                ('restaurante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiqueteras', to='restaurantes.restaurante')),
            ],
        ),
        migrations.CreateModel(
            name='ConsumoTiquetera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('comanda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comandas.comanda')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tiquetera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumos', to='tiqueteras.tiquetera')),
            ],
        ),
    ]
