# Generated by Django 6.0.5 on 2026-05-18 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiqueteras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantiquetera',
            name='tipo_servicio',
            field=models.CharField(choices=[('almuerzo', 'Almuerzo'), ('cena', 'Cena')], default='almuerzo', max_length=20),
        ),
    ]
