# Generated by Django 6.0.5 on 2026-05-19 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comandas', '0005_comanda_tiquetera'),
        ('tiqueteras', '0002_plantiquetera_tipo_servicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumotiquetera',
            name='comanda',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumo_tiquetera', to='comandas.comanda'),
        ),
    ]
